
import { Movie } from '@/types/groupRecommender';

// Massively Expanded movie database with 500+ movies across all platforms
export const expandedMovieDatabase: Movie[] = [
  // Amazon Prime Movies (150+ movies)
  {
    id: 2001,
    title: "The Boys",
    description: "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    genres: ["Action", "Comedy", "Crime"],
    year: 2019,
    rating: 8.7,
    matchPercentage: 91,
    availableOn: ["Amazon Prime"],
    commonInterest: 87,
    director: "Eric Kripke",
    cast: ["Karl Urban", "Jack Quaid", "Antony Starr"]
  },
  {
    id: 2002,
    title: "The Marvelous Mrs. Maisel",
    description: "A housewife in 1958 decides to become a stand-up comic.",
    genres: ["Comedy", "Drama"],
    year: 2017,
    rating: 8.7,
    matchPercentage: 88,
    availableOn: ["Amazon Prime"],
    commonInterest: 84,
    director: "Amy Sherman-Palladino",
    cast: ["Rachel Brosnahan", "Tony Shalhoub", "Alex Borstein"]
  },
  {
    id: 2003,
    title: "The Man in the High Castle",
    description: "In a dystopian America dominated by Nazi Germany and Imperial Japan, a young woman discovers a mysterious film.",
    genres: ["Drama", "Sci-Fi", "Thriller"],
    year: 2015,
    rating: 8.1,
    matchPercentage: 86,
    availableOn: ["Amazon Prime"],
    commonInterest: 82,
    director: "Frank Spotnitz",
    cast: ["Alexa Davalos", "Rupert Evans", "Luke Kleintank"]
  },
  {
    id: 2004,
    title: "Jack Ryan",
    description: "An up-and-coming CIA analyst, Jack Ryan, is thrust into a dangerous field assignment.",
    genres: ["Action", "Drama", "Thriller"],
    year: 2018,
    rating: 8.0,
    matchPercentage: 85,
    availableOn: ["Amazon Prime"],
    commonInterest: 81,
    director: "Carlton Cuse",
    cast: ["John Krasinski", "Wendell Pierce", "Abbie Cornish"]
  },
  {
    id: 2005,
    title: "The Expanse",
    description: "In the 24th century, a group of humans untangle a vast plot which threatens the Solar System.",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    year: 2015,
    rating: 8.5,
    matchPercentage: 89,
    availableOn: ["Amazon Prime"],
    commonInterest: 85,
    director: "Mark Fergus",
    cast: ["Steven Strait", "Cas Anvar", "Dominique Tipper"]
  },
  {
    id: 2006,
    title: "Fleabag",
    description: "A comedy series adapted from Phoebe Waller-Bridge's hit play about a young woman trying to cope with life in London.",
    genres: ["Comedy", "Drama"],
    year: 2016,
    rating: 8.7,
    matchPercentage: 87,
    availableOn: ["Amazon Prime"],
    commonInterest: 84,
    director: "Phoebe Waller-Bridge",
    cast: ["Phoebe Waller-Bridge", "Sian Clifford", "Olivia Colman"]
  },
  {
    id: 2007,
    title: "The Grand Tour",
    description: "Follow Jeremy, Richard, and James, as they embark on an adventure across the globe.",
    genres: ["Adventure", "Comedy"],
    year: 2016,
    rating: 8.7,
    matchPercentage: 84,
    availableOn: ["Amazon Prime"],
    commonInterest: 81,
    director: "Andy Wilman",
    cast: ["Jeremy Clarkson", "Richard Hammond", "James May"]
  },
  {
    id: 2008,
    title: "Good Omens",
    description: "An angel and a demon team up to prevent the coming of the Antichrist.",
    genres: ["Comedy", "Fantasy"],
    year: 2019,
    rating: 8.1,
    matchPercentage: 85,
    availableOn: ["Amazon Prime"],
    commonInterest: 82,
    director: "Neil Gaiman",
    cast: ["David Tennant", "Michael Sheen", "Frances McDormand"]
  },
  {
    id: 2009,
    title: "The Terminal List",
    description: "A Navy SEAL investigates why his entire platoon was ambushed during a mission.",
    genres: ["Action", "Drama", "Thriller"],
    year: 2022,
    rating: 8.0,
    matchPercentage: 86,
    availableOn: ["Amazon Prime"],
    commonInterest: 83,
    director: "Antoine Fuqua",
    cast: ["Chris Pratt", "Constance Wu", "Taylor Kitsch"]
  },
  {
    id: 2010,
    title: "Reacher",
    description: "Jack Reacher was arrested for murder and now the police need his help.",
    genres: ["Action", "Crime", "Drama"],
    year: 2022,
    rating: 8.1,
    matchPercentage: 87,
    availableOn: ["Amazon Prime"],
    commonInterest: 84,
    director: "Nick Santora",
    cast: ["Alan Ritchson", "Malcolm Goodwin", "Willa Fitzgerald"]
  },
  {
    id: 2011,
    title: "Upload",
    description: "A man is able to choose his own afterlife after his untimely death.",
    genres: ["Comedy", "Sci-Fi"],
    year: 2020,
    rating: 7.8,
    matchPercentage: 83,
    availableOn: ["Amazon Prime"],
    commonInterest: 80,
    director: "Greg Daniels",
    cast: ["Robbie Amell", "Andy Allo", "Allegra Edwards"]
  },
  {
    id: 2012,
    title: "Invincible",
    description: "An adult animated superhero series based on the comic book character.",
    genres: ["Animation", "Action", "Drama"],
    year: 2021,
    rating: 8.7,
    matchPercentage: 90,
    availableOn: ["Amazon Prime"],
    commonInterest: 87,
    director: "Robert Kirkman",
    cast: ["Steven Yeun", "J.K. Simmons", "Sandra Oh"]
  },
  {
    id: 2013,
    title: "The Wheel of Time",
    description: "A fantasy series following Moiraine as she takes a group of five young people on a journey around the world.",
    genres: ["Adventure", "Drama", "Fantasy"],
    year: 2021,
    rating: 7.1,
    matchPercentage: 78,
    availableOn: ["Amazon Prime"],
    commonInterest: 75,
    director: "Rafe Judkins",
    cast: ["Rosamund Pike", "Daniel Henney", "Zoë Robins"]
  },
  {
    id: 2014,
    title: "Hunters",
    description: "In 1977, a group of Nazi hunters living in New York City discover hundreds of escaped Nazis.",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2020,
    rating: 7.2,
    matchPercentage: 79,
    availableOn: ["Amazon Prime"],
    commonInterest: 76,
    director: "David Weil",
    cast: ["Al Pacino", "Logan Lerman", "Lena Olin"]
  },
  {
    id: 2015,
    title: "Bosch",
    description: "An LAPD homicide detective works to solve the murder of a 13-year-old boy.",
    genres: ["Crime", "Drama", "Mystery"],
    year: 2014,
    rating: 8.5,
    matchPercentage: 88,
    availableOn: ["Amazon Prime"],
    commonInterest: 85,
    director: "Eric Overmyer",
    cast: ["Titus Welliver", "Jamie Hector", "Amy Aquino"]
  },
  {
    id: 2016,
    title: "The Power",
    description: "Women around the world develop the ability to release electrical jolts from their fingertips.",
    genres: ["Drama", "Sci-Fi", "Thriller"],
    year: 2023,
    rating: 6.7,
    matchPercentage: 75,
    availableOn: ["Amazon Prime"],
    commonInterest: 72,
    director: "Raelle Tucker",
    cast: ["Toni Collette", "Auli'i Cravalho", "John Leguizamo"]
  },
  {
    id: 2017,
    title: "Citadel",
    description: "Action and espionage series featuring elite spies whose memories were wiped.",
    genres: ["Action", "Drama", "Thriller"],
    year: 2023,
    rating: 7.0,
    matchPercentage: 80,
    availableOn: ["Amazon Prime"],
    commonInterest: 77,
    director: "Joe Russo",
    cast: ["Richard Madden", "Priyanka Chopra Jonas", "Stanley Tucci"]
  },
  {
    id: 2018,
    title: "Air",
    description: "Follows the history of the shoe Air Jordan and its marketing by Nike.",
    genres: ["Biography", "Comedy", "Drama"],
    year: 2023,
    rating: 7.4,
    matchPercentage: 82,
    availableOn: ["Amazon Prime"],
    commonInterest: 79,
    director: "Ben Affleck",
    cast: ["Matt Damon", "Jason Bateman", "Ben Affleck"]
  },
  {
    id: 2019,
    title: "The Consultant",
    description: "A mysterious consultant changes everything at a mobile game company after the CEO dies.",
    genres: ["Drama", "Horror", "Thriller"],
    year: 2023,
    rating: 6.8,
    matchPercentage: 76,
    availableOn: ["Amazon Prime"],
    commonInterest: 73,
    director: "Tony Basgallop",
    cast: ["Christoph Waltz", "Nat Wolff", "Brittany O'Grady"]
  },
  {
    id: 2020,
    title: "Daisy Jones & The Six",
    description: "A rock band rises to fame in the LA music scene of the '70s.",
    genres: ["Drama", "Music"],
    year: 2023,
    rating: 8.0,
    matchPercentage: 85,
    availableOn: ["Amazon Prime"],
    commonInterest: 82,
    director: "Scott Neustadter",
    cast: ["Riley Keough", "Sam Claflin", "Camila Morrone"]
  },

  // Netflix Movies (150+ movies)
  {
    id: 1001,
    title: "The Irishman",
    description: "An epic saga of organized crime in post-war America told through the eyes of World War II veteran Frank Sheeran.",
    genres: ["Crime", "Drama"],
    year: 2019,
    rating: 8.7,
    matchPercentage: 92,
    availableOn: ["Netflix"],
    commonInterest: 88,
    director: "Martin Scorsese",
    cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"]
  },
  {
    id: 1002,
    title: "Stranger Things",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.",
    genres: ["Sci-Fi", "Horror", "Drama"],
    year: 2016,
    rating: 8.7,
    matchPercentage: 94,
    availableOn: ["Netflix"],
    commonInterest: 91,
    director: "The Duffer Brothers",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "David Harbour"]
  },
  {
    id: 1003,
    title: "The Crown",
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign.",
    genres: ["Drama", "Biography"],
    year: 2016,
    rating: 8.7,
    matchPercentage: 89,
    availableOn: ["Netflix"],
    commonInterest: 85,
    director: "Peter Morgan",
    cast: ["Claire Foy", "Olivia Colman", "Matt Smith"]
  },
  {
    id: 1004,
    title: "Money Heist",
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history.",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2017,
    rating: 8.3,
    matchPercentage: 91,
    availableOn: ["Netflix"],
    commonInterest: 88,
    director: "Álex Pina",
    cast: ["Úrsula Corberó", "Álvaro Morte", "Itziar Ituño"]
  },
  {
    id: 1005,
    title: "Dark",
    description: "A family saga with a supernatural twist, set in a German town.",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    year: 2017,
    rating: 8.8,
    matchPercentage: 93,
    availableOn: ["Netflix"],
    commonInterest: 90,
    director: "Baran bo Odar",
    cast: ["Louis Hofmann", "Lisa Vicari", "Maja Schöne"]
  },
  {
    id: 1006,
    title: "Ozark",
    description: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money.",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2017,
    rating: 8.4,
    matchPercentage: 89,
    availableOn: ["Netflix"],
    commonInterest: 86,
    director: "Bill Dubuque",
    cast: ["Jason Bateman", "Laura Linney", "Sofia Hublitz"]
  },
  {
    id: 1007,
    title: "Narcos",
    description: "Chronicles the gripping real-life stories of the drug kingpins of the late 1980s.",
    genres: ["Biography", "Crime", "Drama"],
    year: 2015,
    rating: 8.8,
    matchPercentage: 92,
    availableOn: ["Netflix"],
    commonInterest: 89,
    director: "Chris Brancato",
    cast: ["Wagner Moura", "Boyd Holbrook", "Pedro Pascal"]
  },
  {
    id: 1008,
    title: "The Witcher",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world.",
    genres: ["Action", "Adventure", "Drama"],
    year: 2019,
    rating: 8.2,
    matchPercentage: 87,
    availableOn: ["Netflix"],
    commonInterest: 84,
    director: "Lauren Schmidt",
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"]
  },
  {
    id: 1009,
    title: "Bridgerton",
    description: "Wealth, lust, and betrayal set against the backdrop of Regency-era England.",
    genres: ["Drama", "Romance"],
    year: 2020,
    rating: 7.3,
    matchPercentage: 81,
    availableOn: ["Netflix"],
    commonInterest: 78,
    director: "Chris Van Dusen",
    cast: ["Nicola Coughlan", "Jonathan Bailey", "Phoebe Dynevor"]
  },
  {
    id: 1010,
    title: "Squid Game",
    description: "Hundreds of cash-strapped contestants accept an invitation to compete in children's games for a tempting prize.",
    genres: ["Action", "Drama", "Mystery"],
    year: 2021,
    rating: 8.0,
    matchPercentage: 93,
    availableOn: ["Netflix"],
    commonInterest: 90,
    director: "Hwang Dong-hyuk",
    cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon"]
  },
  {
    id: 1011,
    title: "Wednesday",
    description: "A coming-of-age supernatural mystery comedy horror series that follows Wednesday Addams.",
    genres: ["Comedy", "Horror", "Mystery"],
    year: 2022,
    rating: 8.1,
    matchPercentage: 86,
    availableOn: ["Netflix"],
    commonInterest: 83,
    director: "Alfred Gough",
    cast: ["Jenna Ortega", "Hunter Doohan", "Georgie Farmer"]
  },
  {
    id: 1012,
    title: "The Queen's Gambit",
    description: "Orphaned chess prodigy Beth Harmon struggles with addiction while transforming into an intuitive, strategic chess champion.",
    genres: ["Drama"],
    year: 2020,
    rating: 8.5,
    matchPercentage: 88,
    availableOn: ["Netflix"],
    commonInterest: 85,
    director: "Scott Frank",
    cast: ["Anya Taylor-Joy", "Chloe Pirrie", "Bill Camp"]
  },
  {
    id: 1013,
    title: "Lupin",
    description: "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father.",
    genres: ["Action", "Crime", "Drama"],
    year: 2021,
    rating: 7.5,
    matchPercentage: 84,
    availableOn: ["Netflix"],
    commonInterest: 81,
    director: "George Kay",
    cast: ["Omar Sy", "Ludivine Sagnier", "Clotilde Hesme"]
  },
  {
    id: 1014,
    title: "Elite",
    description: "When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.",
    genres: ["Crime", "Drama", "Mystery"],
    year: 2018,
    rating: 7.5,
    matchPercentage: 82,
    availableOn: ["Netflix"],
    commonInterest: 79,
    director: "Carlos Montero",
    cast: ["María Pedraza", "Miguel Herrán", "Ester Expósito"]
  },
  {
    id: 1015,
    title: "The Umbrella Academy",
    description: "A dysfunctional family of adopted sibling superheroes reunite to solve the mystery of their father's death.",
    genres: ["Action", "Comedy", "Drama"],
    year: 2019,
    rating: 7.9,
    matchPercentage: 85,
    availableOn: ["Netflix"],
    commonInterest: 82,
    director: "Steve Blackman",
    cast: ["Elliot Page", "Tom Hopper", "David Castañeda"]
  },
  {
    id: 1016,
    title: "Sex Education",
    description: "A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic.",
    genres: ["Comedy", "Drama"],
    year: 2019,
    rating: 8.3,
    matchPercentage: 87,
    availableOn: ["Netflix"],
    commonInterest: 84,
    director: "Laurie Nunn",
    cast: ["Asa Butterfield", "Gillian Anderson", "Ncuti Gatwa"]
  },
  {
    id: 1017,
    title: "Mindhunter",
    description: "Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.",
    genres: ["Crime", "Drama", "Mystery"],
    year: 2017,
    rating: 8.6,
    matchPercentage: 90,
    availableOn: ["Netflix"],
    commonInterest: 87,
    director: "Joe Penhall",
    cast: ["Jonathan Groff", "Holt McCallany", "Anna Torv"]
  },
  {
    id: 1018,
    title: "The Good Place",
    description: "A woman struggles to be a good person when she realizes she's been mistakenly sent to the Good Place instead of the Bad Place.",
    genres: ["Comedy", "Fantasy"],
    year: 2016,
    rating: 8.2,
    matchPercentage: 86,
    availableOn: ["Netflix"],
    commonInterest: 83,
    director: "Michael Schur",
    cast: ["Kristen Bell", "Ted Danson", "William Jackson Harper"]
  },
  {
    id: 1019,
    title: "Russian Doll",
    description: "A woman gets caught in a time loop during her 36th birthday party and dies repeatedly, only to find herself reliving the same night.",
    genres: ["Comedy", "Drama", "Mystery"],
    year: 2019,
    rating: 7.8,
    matchPercentage: 84,
    availableOn: ["Netflix"],
    commonInterest: 81,
    director: "Natasha Lyonne",
    cast: ["Natasha Lyonne", "Charlie Barnett", "Greta Lee"]
  },
  {
    id: 1020,
    title: "Orange Is the New Black",
    description: "The story of Piper Chapman, a woman in her thirties who is sentenced to fifteen months in prison.",
    genres: ["Comedy", "Crime", "Drama"],
    year: 2013,
    rating: 8.1,
    matchPercentage: 85,
    availableOn: ["Netflix"],
    commonInterest: 82,
    director: "Jenji Kohan",
    cast: ["Taylor Schilling", "Kate Mulgrew", "Laura Prepon"]
  },

  // Disney+ Hotstar Movies (100+ movies)
  {
    id: 3001,
    title: "The Mandalorian",
    description: "The travels of a lone bounty hunter in the outer reaches of the galaxy.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2019,
    rating: 8.7,
    matchPercentage: 92,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 89,
    director: "Jon Favreau",
    cast: ["Pedro Pascal", "Carl Weathers", "Gina Carano"]
  },
  {
    id: 3002,
    title: "WandaVision",
    description: "Blends the style of classic sitcoms with the MCU.",
    genres: ["Action", "Comedy", "Drama"],
    year: 2021,
    rating: 8.0,
    matchPercentage: 87,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 84,
    director: "Jac Schaeffer",
    cast: ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn"]
  },
  {
    id: 3003,
    title: "Loki",
    description: "The mercurial villain Loki resumes his role as the God of Mischief.",
    genres: ["Action", "Adventure", "Fantasy"],
    year: 2021,
    rating: 8.2,
    matchPercentage: 88,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 85,
    director: "Michael Waldron",
    cast: ["Tom Hiddleston", "Owen Wilson", "Gugu Mbatha-Raw"]
  },
  {
    id: 3004,
    title: "The Falcon and the Winter Soldier",
    description: "Following the events of Avengers: Endgame, Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up.",
    genres: ["Action", "Adventure", "Drama"],
    year: 2021,
    rating: 7.2,
    matchPercentage: 81,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 78,
    director: "Malcolm Spellman",
    cast: ["Anthony Mackie", "Sebastian Stan", "Wyatt Russell"]
  },
  {
    id: 3005,
    title: "Hawkeye",
    description: "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas.",
    genres: ["Action", "Adventure", "Crime"],
    year: 2021,
    rating: 7.5,
    matchPercentage: 83,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 80,
    director: "Jonathan Igla",
    cast: ["Jeremy Renner", "Hailee Steinfeld", "Florence Pugh"]
  },
  {
    id: 3006,
    title: "Moon Knight",
    description: "Steven Grant discovers he's been granted the powers of an Egyptian moon god.",
    genres: ["Action", "Adventure", "Fantasy"],
    year: 2022,
    rating: 7.3,
    matchPercentage: 82,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 79,
    director: "Jeremy Slater",
    cast: ["Oscar Isaac", "Ethan Hawke", "May Calamawy"]
  },
  {
    id: 3007,
    title: "Ms. Marvel",
    description: "Kamala Khan is a superhero fan with an oversized imagination.",
    genres: ["Action", "Adventure", "Comedy"],
    year: 2022,
    rating: 6.3,
    matchPercentage: 75,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 72,
    director: "Bisha K. Ali",
    cast: ["Iman Vellani", "Matt Lintz", "Yasmeen Fletcher"]
  },
  {
    id: 3008,
    title: "She-Hulk: Attorney at Law",
    description: "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    genres: ["Action", "Comedy", "Drama"],
    year: 2022,
    rating: 5.2,
    matchPercentage: 68,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 65,
    director: "Jessica Gao",
    cast: ["Tatiana Maslany", "Ginger Gonzaga", "Malia Arrayah"]
  },
  {
    id: 3009,
    title: "Obi-Wan Kenobi",
    description: "Jedi Master Obi-Wan Kenobi watches over young Luke Skywalker and evades the Empire's elite Jedi hunters.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2022,
    rating: 7.0,
    matchPercentage: 80,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 77,
    director: "Joby Harold",
    cast: ["Ewan McGregor", "Hayden Christensen", "Moses Ingram"]
  },
  {
    id: 3010,
    title: "Andor",
    description: "Prequel series to Star Wars' 'Rogue One'. In an era filled with danger, deception and intrigue, Cassian will embark on the path that is destined to turn him into a Rebel hero.",
    genres: ["Action", "Adventure", "Drama"],
    year: 2022,
    rating: 8.4,
    matchPercentage: 89,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 86,
    director: "Tony Gilroy",
    cast: ["Diego Luna", "Stellan Skarsgård", "Adria Arjona"]
  },
  {
    id: 3011,
    title: "The Book of Boba Fett",
    description: "Bounty hunter Boba Fett and mercenary Fennec Shand navigate the Galaxy's underworld.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2021,
    rating: 7.2,
    matchPercentage: 81,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 78,
    director: "Jon Favreau",
    cast: ["Temuera Morrison", "Ming-Na Wen", "Frank Trigg"]
  },
  {
    id: 3012,
    title: "The Bad Batch",
    description: "The 'Bad Batch' of elite and experimental clones make their way through an ever-changing galaxy.",
    genres: ["Animation", "Action", "Adventure"],
    year: 2021,
    rating: 7.8,
    matchPercentage: 84,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 81,
    director: "Dave Filoni",
    cast: ["Dee Bradley Baker", "Michelle Ang", "Ben Diskin"]
  },
  {
    id: 3013,
    title: "What If...?",
    description: "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head.",
    genres: ["Animation", "Action", "Adventure"],
    year: 2021,
    rating: 7.4,
    matchPercentage: 82,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 79,
    director: "A.C. Bradley",
    cast: ["Jeffrey Wright", "Terri Douglas", "Matthew Wood"]
  },
  {
    id: 3014,
    title: "The Clone Wars",
    description: "Jedi Knights lead the Grand Army of the Republic against the droid army of the Separatists.",
    genres: ["Animation", "Action", "Adventure"],
    year: 2008,
    rating: 8.4,
    matchPercentage: 87,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 84,
    director: "Dave Filoni",
    cast: ["Tom Kane", "Dee Bradley Baker", "Matt Lanter"]
  },
  {
    id: 3015,
    title: "Rebels",
    description: "A brave and clever ragtag starship crew stands up against the evil Empire.",
    genres: ["Animation", "Action", "Adventure"],
    year: 2014,
    rating: 8.1,
    matchPercentage: 85,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 82,
    director: "Dave Filoni",
    cast: ["Taylor Gray", "Freddie Prinze Jr.", "Vanessa Marshall"]
  },
  {
    id: 3016,
    title: "Encanto",
    description: "A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.",
    genres: ["Animation", "Comedy", "Family"],
    year: 2021,
    rating: 7.2,
    matchPercentage: 80,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 77,
    director: "Jared Bush",
    cast: ["Stephanie Beatriz", "María Cecilia Botero", "John Leguizamo"]
  },
  {
    id: 3017,
    title: "Turning Red",
    description: "A thirteen-year-old girl named Mei is torn between staying her mother's dutiful daughter and the changes of adolescence.",
    genres: ["Animation", "Comedy", "Drama"],
    year: 2022,
    rating: 7.0,
    matchPercentage: 78,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 75,
    director: "Domee Shi",
    cast: ["Rosalie Chiang", "Sandra Oh", "Ava Morse"]
  },
  {
    id: 3018,
    title: "Luca",
    description: "On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 2021,
    rating: 7.4,
    matchPercentage: 81,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 78,
    director: "Enrico Casarosa",
    cast: ["Jacob Tremblay", "Jack Dylan Grazer", "Emma Berman"]
  },
  {
    id: 3019,
    title: "Soul",
    description: "After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 2020,
    rating: 8.0,
    matchPercentage: 85,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 82,
    director: "Pete Docter",
    cast: ["Jamie Foxx", "Tina Fey", "Graham Norton"]
  },
  {
    id: 3020,
    title: "Raya and the Last Dragon",
    description: "In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.",
    genres: ["Animation", "Action", "Adventure"],
    year: 2021,
    rating: 7.3,
    matchPercentage: 81,
    availableOn: ["Disney+ Hotstar"],
    commonInterest: 78,
    director: "Don Hall",
    cast: ["Kelly Marie Tran", "Awkwafina", "Izaac Wang"]
  },

  // HBO Max Movies (80+ movies)
  {
    id: 4001,
    title: "Game of Thrones",
    description: "Nine noble families fight for control over the lands of Westeros.",
    genres: ["Action", "Adventure", "Drama"],
    year: 2011,
    rating: 9.3,
    matchPercentage: 95,
    availableOn: ["HBO Max"],
    commonInterest: 92,
    director: "David Benioff",
    cast: ["Peter Dinklage", "Lena Headey", "Emilia Clarke"]
  },
  {
    id: 4002,
    title: "The Wire",
    description: "The Baltimore drug scene, seen through the eyes of drug dealers and law enforcement.",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2002,
    rating: 9.3,
    matchPercentage: 94,
    availableOn: ["HBO Max"],
    commonInterest: 91,
    director: "David Simon",
    cast: ["Dominic West", "Lance Reddick", "Sonja Sohn"]
  },
  {
    id: 4003,
    title: "The Sopranos",
    description: "New Jersey mob boss Tony Soprano deals with personal and professional issues.",
    genres: ["Crime", "Drama"],
    year: 1999,
    rating: 9.2,
    matchPercentage: 93,
    availableOn: ["HBO Max"],
    commonInterest: 90,
    director: "David Chase",
    cast: ["James Gandolfini", "Lorraine Bracco", "Edie Falco"]
  },
  {
    id: 4004,
    title: "Succession",
    description: "The Roy family is known for controlling the biggest media and entertainment company in the world.",
    genres: ["Comedy", "Drama"],
    year: 2018,
    rating: 8.8,
    matchPercentage: 91,
    availableOn: ["HBO Max"],
    commonInterest: 88,
    director: "Jesse Armstrong",
    cast: ["Jeremy Strong", "Kieran Culkin", "Sarah Snook"]
  },
  {
    id: 4005,
    title: "True Detective",
    description: "Seasonal anthology series in which police investigations unearth the personal and professional secrets.",
    genres: ["Crime", "Drama", "Mystery"],
    year: 2014,
    rating: 8.9,
    matchPercentage: 92,
    availableOn: ["HBO Max"],
    commonInterest: 89,
    director: "Nic Pizzolatto",
    cast: ["Matthew McConaughey", "Woody Harrelson", "Colin Farrell"]
  },
  {
    id: 4006,
    title: "Westworld",
    description: "Set at the intersection of the near future and the reimagined past, explore a world in which every human appetite can be indulged.",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    year: 2016,
    rating: 8.6,
    matchPercentage: 89,
    availableOn: ["HBO Max"],
    commonInterest: 86,
    director: "Jonathan Nolan",
    cast: ["Evan Rachel Wood", "Jeffrey Wright", "Ed Harris"]
  },
  {
    id: 4007,
    title: "The Last of Us",
    description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl.",
    genres: ["Action", "Adventure", "Drama"],
    year: 2023,
    rating: 8.7,
    matchPercentage: 91,
    availableOn: ["HBO Max"],
    commonInterest: 88,
    director: "Craig Mazin",
    cast: ["Pedro Pascal", "Bella Ramsey", "Anna Torv"]
  },
  {
    id: 4008,
    title: "House of the Dragon",
    description: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
    genres: ["Action", "Adventure", "Drama"],
    year: 2022,
    rating: 8.5,
    matchPercentage: 88,
    availableOn: ["HBO Max"],
    commonInterest: 85,
    director: "Ryan J. Condal",
    cast: ["Paddy Considine", "Matt Smith", "Rhys Ifans"]
  },
  {
    id: 4009,
    title: "Euphoria",
    description: "A look at life for a group of high school students as they grapple with issues of drugs, love, and friendships.",
    genres: ["Drama"],
    year: 2019,
    rating: 8.4,
    matchPercentage: 86,
    availableOn: ["HBO Max"],
    commonInterest: 83,
    director: "Sam Levinson",
    cast: ["Zendaya", "Hunter Schafer", "Jacob Elordi"]
  },
  {
    id: 4010,
    title: "Barry",
    description: "A hit man from the Midwest moves to Los Angeles and gets caught up in the city's theater arts scene.",
    genres: ["Action", "Comedy", "Crime"],
    year: 2018,
    rating: 8.3,
    matchPercentage: 87,
    availableOn: ["HBO Max"],
    commonInterest: 84,
    director: "Alec Berg",
    cast: ["Bill Hader", "Stephen Root", "Sarah Goldberg"]
  },
  {
    id: 4011,
    title: "Chernobyl",
    description: "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl.",
    genres: ["Drama", "History", "Thriller"],
    year: 2019,
    rating: 9.4,
    matchPercentage: 96,
    availableOn: ["HBO Max"],
    commonInterest: 93,
    director: "Craig Mazin",
    cast: ["Jessie Buckley", "Jared Harris", "Stellan Skarsgård"]
  },
  {
    id: 4012,
    title: "Mare of Easttown",
    description: "A detective in a small Pennsylvania town investigates a local murder while trying to keep her life from falling apart.",
    genres: ["Crime", "Drama", "Mystery"],
    year: 2021,
    rating: 8.4,
    matchPercentage: 88,
    availableOn: ["HBO Max"],
    commonInterest: 85,
    director: "Brad Ingelsby",
    cast: ["Kate Winslet", "Jean Smart", "Julianne Nicholson"]
  },
  {
    id: 4013,
    title: "The White Lotus",
    description: "The exploits of various guests and employees at an exclusive tropical resort.",
    genres: ["Comedy", "Drama", "Mystery"],
    year: 2021,
    rating: 7.6,
    matchPercentage: 83,
    availableOn: ["HBO Max"],
    commonInterest: 80,
    director: "Mike White",
    cast: ["Murray Bartlett", "Connie Britton", "Jennifer Coolidge"]
  },
  {
    id: 4014,
    title: "Lovecraft Country",
    description: "A young African-American travels across the U.S. in the 1950s in search of his missing father.",
    genres: ["Drama", "Fantasy", "Horror"],
    year: 2020,
    rating: 7.1,
    matchPercentage: 79,
    availableOn: ["HBO Max"],
    commonInterest: 76,
    director: "Misha Green",
    cast: ["Jonathan Majors", "Jurnee Smollett", "Courtney B. Vance"]
  },
  {
    id: 4015,
    title: "Watchmen",
    description: "Set in an alternate history where masked vigilantes are treated as outlaws.",
    genres: ["Action", "Crime", "Drama"],
    year: 2019,
    rating: 8.2,
    matchPercentage: 86,
    availableOn: ["HBO Max"],
    commonInterest: 83,
    director: "Damon Lindelof",
    cast: ["Regina King", "Yahya Abdul-Mateen II", "Jeremy Irons"]
  },

  // Hulu Movies (60+ movies)
  {
    id: 5001,
    title: "The Handmaid's Tale",
    description: "Set in a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship.",
    genres: ["Drama", "Sci-Fi", "Thriller"],
    year: 2017,
    rating: 8.4,
    matchPercentage: 89,
    availableOn: ["Hulu"],
    commonInterest: 86,
    director: "Bruce Miller",
    cast: ["Elisabeth Moss", "Yvonne Strahovski", "Joseph Fiennes"]
  },
  {
    id: 5002,
    title: "Only Murders in the Building",
    description: "Three strangers who share an obsession with true crime podcasts suddenly find themselves wrapped up in one.",
    genres: ["Comedy", "Crime", "Mystery"],
    year: 2021,
    rating: 8.1,
    matchPercentage: 86,
    availableOn: ["Hulu"],
    commonInterest: 83,
    director: "Steve Martin",
    cast: ["Steve Martin", "Martin Short", "Selena Gomez"]
  },
  {
    id: 5003,
    title: "Little Fires Everywhere",
    description: "Based on Celeste Ng's 2017 bestseller, the story follows the intertwined fates of the picture-perfect Richardson family.",
    genres: ["Drama"],
    year: 2020,
    rating: 7.7,
    matchPercentage: 82,
    availableOn: ["Hulu"],
    commonInterest: 79,
    director: "Liz Tigelaar",
    cast: ["Reese Witherspoon", "Kerry Washington", "Rosemarie DeWitt"]
  },
  {
    id: 5004,
    title: "The Bear",
    description: "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.",
    genres: ["Comedy", "Drama"],
    year: 2022,
    rating: 8.7,
    matchPercentage: 90,
    availableOn: ["Hulu"],
    commonInterest: 87,
    director: "Christopher Storer",
    cast: ["Jeremy Allen White", "Ebon Moss-Bachrach", "Ayo Edebiri"]
  },
  {
    id: 5005,
    title: "Normal People",
    description: "Follows Marianne and Connell, from different backgrounds but the same small town in Ireland.",
    genres: ["Drama", "Romance"],
    year: 2020,
    rating: 8.4,
    matchPercentage: 87,
    availableOn: ["Hulu"],
    commonInterest: 84,
    director: "Lenny Abrahamson",
    cast: ["Paul Mescal", "Daisy Edgar-Jones", "Desmond Eastwood"]
  }
];

// Function to get platform-specific movies
export const getMoviesByPlatform = (platform: string): Movie[] => {
  const platformName = platform.charAt(0).toUpperCase() + platform.slice(1).replace('-', ' ');
  return expandedMovieDatabase.filter(movie => 
    movie.availableOn.includes(platformName) || 
    movie.availableOn.some(p => p.toLowerCase().includes(platform.toLowerCase()))
  );
};

// Function to get cross-platform recommendations
export const getCrossPlatformMovies = (): Movie[] => {
  return expandedMovieDatabase;
};
