
import { Movie } from '@/types/groupRecommender';

export const movieDatabase: Movie[] = [
  // Netflix Movies
  { id: 1, title: 'Extraction', description: 'A black-market mercenary who has nothing to lose is hired to rescue the kidnapped son of an imprisoned international crime lord.', genres: ['Action', 'Thriller'], year: 2020, rating: 4.1, matchPercentage: 89, availableOn: ['Netflix'], commonInterest: 85, director: 'Sam Hargrave', cast: ['Chris Hemsworth', 'Rudhraksh Jaiswal'] },
  { id: 2, title: 'The Old Guard', description: 'A covert team of immortal mercenaries are suddenly exposed and must now fight to keep their identity a secret.', genres: ['Action', 'Fantasy'], year: 2020, rating: 4.0, matchPercentage: 87, availableOn: ['Netflix'], commonInterest: 82, director: 'Gina Prince-Bythewood', cast: ['Charlize Theron', 'KiKi Layne'] },
  { id: 4, title: 'The Kissing Booth', description: 'A high school student is forced to confront her secret crush at a kissing booth.', genres: ['Romance', 'Comedy'], year: 2018, rating: 3.8, matchPercentage: 76, availableOn: ['Netflix'], commonInterest: 72, director: 'Vince Marcello', cast: ['Joey King', 'Jacob Elordi'] },
  { id: 5, title: 'To All the Boys I\'ve Loved Before', description: 'A teenage girl\'s secret love letters are exposed and wreak havoc on her love life.', genres: ['Romance', 'Comedy'], year: 2018, rating: 4.2, matchPercentage: 85, availableOn: ['Netflix'], commonInterest: 81, director: 'Susan Johnson', cast: ['Lana Condor', 'Noah Centineo'] },
  { id: 8, title: 'Hereditary', description: 'A grieving family is haunted by tragedy and disturbing secrets.', genres: ['Horror', 'Drama'], year: 2018, rating: 4.1, matchPercentage: 86, availableOn: ['Netflix'], commonInterest: 80, director: 'Ari Aster', cast: ['Toni Collette', 'Gabriel Byrne'] },
  { id: 10, title: 'The Hangover', description: 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night.', genres: ['Comedy'], year: 2009, rating: 4.2, matchPercentage: 84, availableOn: ['Netflix'], commonInterest: 79, director: 'Todd Phillips', cast: ['Bradley Cooper', 'Ed Helms'] },
  { id: 13, title: 'Blade Runner 2049', description: 'A young blade runner discovers a secret that could plunge what\'s left of society into chaos.', genres: ['Sci-Fi', 'Drama'], year: 2017, rating: 4.6, matchPercentage: 93, availableOn: ['Netflix'], commonInterest: 90, director: 'Denis Villeneuve', cast: ['Ryan Gosling', 'Harrison Ford'] },
  
  // Amazon Prime Movies
  { id: 3, title: 'John Wick', description: 'An ex-hit-man comes out of retirement to track down the gangsters that took everything from him.', genres: ['Action', 'Crime'], year: 2014, rating: 4.3, matchPercentage: 91, availableOn: ['Amazon Prime Video'], commonInterest: 88, director: 'Chad Stahelski', cast: ['Keanu Reeves', 'Michael Nyqvist'] },
  { id: 6, title: 'The Notebook', description: 'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom.', genres: ['Romance', 'Drama'], year: 2004, rating: 4.5, matchPercentage: 92, availableOn: ['Amazon Prime Video'], commonInterest: 89, director: 'Nick Cassavetes', cast: ['Ryan Gosling', 'Rachel McAdams'] },
  { id: 12, title: 'Knives Out', description: 'A detective investigates the death of a patriarch of an eccentric, combative family.', genres: ['Comedy', 'Crime', 'Mystery'], year: 2019, rating: 4.4, matchPercentage: 89, availableOn: ['Amazon Prime Video'], commonInterest: 85, director: 'Rian Johnson', cast: ['Daniel Craig', 'Chris Evans'] },
  { id: 14, title: 'Interstellar', description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', genres: ['Sci-Fi', 'Drama'], year: 2014, rating: 4.7, matchPercentage: 95, availableOn: ['Amazon Prime Video'], commonInterest: 92, director: 'Christopher Nolan', cast: ['Matthew McConaughey', 'Anne Hathaway'] },
  { id: 16, title: 'Saving Private Ryan', description: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper.', genres: ['War', 'Drama'], year: 1998, rating: 4.8, matchPercentage: 96, availableOn: ['Amazon Prime Video'], commonInterest: 94, director: 'Steven Spielberg', cast: ['Tom Hanks', 'Matt Damon'] },
  { id: 20, title: 'Forrest Gump', description: 'The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an IQ of 75.', genres: ['Drama', 'Romance'], year: 1994, rating: 4.7, matchPercentage: 94, availableOn: ['Amazon Prime Video'], commonInterest: 91, director: 'Robert Zemeckis', cast: ['Tom Hanks', 'Robin Wright'] },
  
  // Disney+ Hotstar Movies
  { id: 21, title: 'Spider-Man: Into the Spider-Verse', description: 'Teen Miles Morales becomes Spider-Man and must save the city from Kingpin.', genres: ['Animation', 'Action', 'Adventure'], year: 2018, rating: 4.6, matchPercentage: 93, availableOn: ['Disney+ Hotstar'], commonInterest: 90, director: 'Peter Ramsey', cast: ['Shameik Moore', 'Jake Johnson'] },
  { id: 26, title: 'The Grand Budapest Hotel', description: 'The adventures of a legendary concierge at a famous European hotel.', genres: ['Comedy', 'Adventure'], year: 2014, rating: 4.2, matchPercentage: 85, availableOn: ['Disney+ Hotstar'], commonInterest: 81, director: 'Wes Anderson', cast: ['Ralph Fiennes', 'F. Murray Abraham'] },
  { id: 28, title: 'The Avengers', description: 'Earth\'s mightiest heroes must come together to stop an alien invasion.', genres: ['Action', 'Adventure', 'Sci-Fi'], year: 2012, rating: 4.5, matchPercentage: 92, availableOn: ['Disney+ Hotstar'], commonInterest: 89, director: 'Joss Whedon', cast: ['Robert Downey Jr.', 'Chris Evans'] },
  
  // Additional movies for other platforms
  { id: 7, title: 'The Conjuring', description: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.', genres: ['Horror', 'Mystery'], year: 2013, rating: 4.4, matchPercentage: 88, availableOn: ['HBO Max'], commonInterest: 84, director: 'James Wan', cast: ['Patrick Wilson', 'Vera Farmiga'] },
  { id: 9, title: 'A Quiet Place', description: 'A family lives in silence to avoid creatures that hunt by sound.', genres: ['Horror', 'Thriller'], year: 2018, rating: 4.3, matchPercentage: 90, availableOn: ['Paramount+'], commonInterest: 87, director: 'John Krasinski', cast: ['Emily Blunt', 'John Krasinski'] },
  { id: 11, title: 'Superbad', description: 'Two co-dependent high school seniors are forced to deal with separation anxiety.', genres: ['Comedy'], year: 2007, rating: 4.0, matchPercentage: 82, availableOn: ['Hulu'], commonInterest: 77, director: 'Greg Mottola', cast: ['Jonah Hill', 'Michael Cera'] },
  { id: 15, title: 'The Matrix', description: 'A computer programmer discovers that reality as he knows it is a simulation.', genres: ['Sci-Fi', 'Action'], year: 1999, rating: 4.5, matchPercentage: 91, availableOn: ['HBO Max'], commonInterest: 88, director: 'The Wachowskis', cast: ['Keanu Reeves', 'Laurence Fishburne'] },
  { id: 17, title: '1917', description: 'Two British soldiers are given an impossible mission during World War I.', genres: ['War', 'Drama'], year: 2019, rating: 4.5, matchPercentage: 92, availableOn: ['Netflix'], commonInterest: 89, director: 'Sam Mendes', cast: ['George MacKay', 'Dean-Charles Chapman'] },
  { id: 18, title: 'Dunkirk', description: 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army.', genres: ['War', 'Drama'], year: 2017, rating: 4.3, matchPercentage: 88, availableOn: ['HBO Max'], commonInterest: 85, director: 'Christopher Nolan', cast: ['Fionn Whitehead', 'Barry Keoghan'] },
  { id: 19, title: 'The Shawshank Redemption', description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption.', genres: ['Drama'], year: 1994, rating: 4.9, matchPercentage: 98, availableOn: ['Netflix'], commonInterest: 96, director: 'Frank Darabont', cast: ['Tim Robbins', 'Morgan Freeman'] },
  { id: 22, title: 'Parasite', description: 'A poor family schemes to become employed by a wealthy family.', genres: ['Thriller', 'Drama'], year: 2019, rating: 4.8, matchPercentage: 96, availableOn: ['Hulu'], commonInterest: 94, director: 'Bong Joon-ho', cast: ['Song Kang-ho', 'Lee Sun-kyun'] },
  { id: 23, title: 'Get Out', description: 'A young African-American visits his white girlfriend\'s parents for the weekend.', genres: ['Horror', 'Thriller'], year: 2017, rating: 4.4, matchPercentage: 89, availableOn: ['Netflix'], commonInterest: 86, director: 'Jordan Peele', cast: ['Daniel Kaluuya', 'Allison Williams'] },
  { id: 24, title: 'Mad Max: Fury Road', description: 'In a post-apocalyptic wasteland, Max teams up with a mysterious woman.', genres: ['Action', 'Adventure'], year: 2015, rating: 4.5, matchPercentage: 91, availableOn: ['HBO Max'], commonInterest: 88, director: 'George Miller', cast: ['Tom Hardy', 'Charlize Theron'] },
  { id: 25, title: 'La La Land', description: 'A jazz musician and an aspiring actress meet and fall in love in Los Angeles.', genres: ['Romance', 'Music'], year: 2016, rating: 4.3, matchPercentage: 87, availableOn: ['Netflix'], commonInterest: 83, director: 'Damien Chazelle', cast: ['Ryan Gosling', 'Emma Stone'] },
  { id: 27, title: 'Moonlight', description: 'A young African-American man grapples with his identity and sexuality.', genres: ['Drama'], year: 2016, rating: 4.4, matchPercentage: 88, availableOn: ['Netflix'], commonInterest: 85, director: 'Barry Jenkins', cast: ['Mahershala Ali', 'Naomie Harris'] },
  { id: 29, title: 'Pulp Fiction', description: 'The lives of two mob hitmen, a boxer, and others intertwine in Los Angeles.', genres: ['Crime', 'Drama'], year: 1994, rating: 4.7, matchPercentage: 94, availableOn: ['Netflix'], commonInterest: 91, director: 'Quentin Tarantino', cast: ['John Travolta', 'Samuel L. Jackson'] },
  { id: 30, title: 'The Dark Knight', description: 'Batman must accept one of the greatest psychological and physical tests.', genres: ['Action', 'Crime', 'Drama'], year: 2008, rating: 4.8, matchPercentage: 96, availableOn: ['HBO Max'], commonInterest: 94, director: 'Christopher Nolan', cast: ['Christian Bale', 'Heath Ledger'] }
];

export const availableGenres = [
  'Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary',
  'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance',
  'Sci-Fi', 'Thriller', 'War', 'Western'
];

export const availablePlatforms = [
  'Netflix', 'Amazon Prime Video', 'Disney+ Hotstar', 'ZEE5', 'Voot', 
  'Hulu', 'HBO Max', 'Apple TV+', 'Paramount+', 'Peacock'
];
